"use client"
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import "@/styles/globals.css";
import {Providers} from "./providers";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Header from "./components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const [header, setHeader] = useState<Boolean>(true);
  // const pathname = usePathname();
  // useEffect(() => {
  //     if(pathname.startsWith('/auth')){
  //       setHeader(false)
  //     }else{
  //       setHeader(true)
  //     }
  // }, [pathname])
  return (
    <html lang="en" className='light'>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Providers>
        {/* {header && <Header/>} */}
        {children}
      </Providers>
      </body>
    </html>
  );
}
